name: CLI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-cli:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js (adjust version to match your project)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify the Node.js version used in your project

      # Install Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Copy environment files
      - name: Copy environment files
        run: |
          cp .env.example .env
          cp .env.example apps/web/.env.local
          cp .env.example packages/db/.env

      # Start Docker services
      - name: Start Docker Compose services
        run: |
          docker compose up -d
        env:
          DOCKER_BUILDKIT: 1 # Enable BuildKit for faster builds

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Set up database
      - name: Set up database
        run: |
          npm run db:generate
          npm run db:migrate -- --name init
          npm run db:seed

      # Run the web app in the background
      - name: Start web app
        run: npm run dev &
        env:
          CI: true # Ensure dev command runs in a non-interactive mode

      # Wait for the app to start (adjust sleep duration as needed)
      - name: Wait for app to be ready
        run: sleep 10

      # Test if the app is running (example: check if the app is accessible)
      - name: Test web app
        run: |
          curl --fail http://localhost:3000 || exit 1 # Adjust port if needed

      # Clean up Docker services
      - name: Clean up
        if: always() # Run even if previous steps fail
        run: docker compose down
